#!/bin/bash
#
# Copyright 2007-2009 3M. All rights reserved.
#
# This script removes the MT7 touch screen driver installation
# During removal, all directories must be writeable.
#

# Stop the driver
[ -e /usr/lib/libTwDrvFifo.so ] && /home/tux/twscreen/TwDriver stop

# Clean out the X input driver
if [ x/usr/lib/xorg/modules/input != x ]
then
   /home/tux/twscreen/TWXinputInstall.perl -remove
   rm -f /usr/lib/xorg/modules/input/twxinput_drv.*
fi

# Remove the xinit scripts
if [ -e /etc/X11/xinit/xinitrc.d/50MT7-xinit ]
then
   rm -f /etc/X11/xinit/xinitrc.d/50MT7-xinit
fi
if [ -e /etc/X11/Xsession.d/50MT7-xinit ]
then
   rm -f /etc/X11/Xsession.d/50MT7-xinit
fi
if [ x != x ]
then
   if [ -e /50MT7-xinit ]
   then
      rm -f /50MT7-xinit
   fi
fi

# Remove the library links
perl /home/tux/twscreen/TwLibInstall.perl remove /usr/lib /home/tux/twscreen/lib*.so
perl /home/tux/twscreen/TwLibInstall.perl remove /usr/lib /home/tux/twscreen/so5/lib*.so

if [ -h /usr/lib64/libTwDrvFifo.so ]
then
    perl /home/tux/twscreen/TwLibInstall.perl remove /usr/lib64 /home/tux/twscreen/x64/libTwDrvFifo.so
fi

if [ -h /usr/lib32/libTwDrvFifo.so ]
then
    perl /home/tux/twscreen/TwLibInstall.perl remove /usr/lib32 /home/tux/twscreen/libTwDrvFifo.so
fi

# Remove any symbolic links
rm -f /home/tux/twscreen/TwMonitor

# Clean out udev and hotplug
[ -e /etc/udev/rules.d/99-TwDriver.rules ] && rm -f /etc/udev/rules.d/99-TwDriver.rules
if [ -e /etc/hotplug/usb/TwHotplug ]
then
   rm -f /etc/hotplug/usb/TwHotplug
   sed /TwHotplug/d /etc/hotplug/usb.usermap >/etc/hotplug/usb.usermap.TEMP
   rm -f /etc/hotplug/usb.usermap
   mv /etc/hotplug/usb.usermap.TEMP /etc/hotplug/usb.usermap
fi

# Remove the init script
if [ -e /etc/init.d/TWDrvStartup ]
then
   if perl /home/tux/twscreen/TwIsThere.perl chkconfig
   then
      if [ -f TwPathAppend.sh ]
      then
         . TwPathAppend.sh
         rm TwPathAppend.sh
      fi
      chkconfig --del TWDrvStartup >/dev/null
      rm -f /etc/init.d/TWDrvStartup
   elif perl /home/tux/twscreen/TwIsThere.perl update-rc.d
   then
      if [ -f TwPathAppend.sh ]
      then
         . TwPathAppend.sh
         rm TwPathAppend.sh
      fi
      rm -f /etc/init.d/TWDrvStartup
      update-rc.d TWDrvStartup remove >/dev/null
   elif perl /home/tux/twscreen/TwIsThere.perl update-rc
   then
      if [ -f TwPathAppend.sh ]
      then
         . TwPathAppend.sh
         rm TwPathAppend.sh
      fi
      rm -f /etc/init.d/TWDrvStartup
      update-rc TWDrvStartup delete >/dev/null
   elif [ -e /etc/init.d/rc.local ]
   then
      rm -f /etc/init.d/TWDrvStartup
      sed /TWDrvStartup/d /etc/init.d/rc.local >/etc/init.d/rc.local.TEMP
      rm -f /etc/init.d/rc.local
      mv /etc/init.d/rc.local.TEMP /etc/init.d/rc.local
   else
      rm -f /etc/init.d/TWDrvStartup
      echo "Need to manually remove the TWDrvStartup init script"
   fi
fi

# Clean out the data directory
if [ -e /home/tux/twscreen/data ]
then
   rm -r /home/tux/twscreen/data/*
   if [ -h /home/tux/twscreen/data ]
   then
      rm -f /home/tux/twscreen/data
   else
      rmdir /home/tux/twscreen/data
   fi
fi
